apiVersion: v1
kind: Service
metadata:
  name: secureworks-frontend-svc
  namespace: secureworks
spec:
  type: NodePort
  selector:
    app: secureworks-frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
