apiVersion: v1
kind: Service
metadata:
  name: secureworks-frontend-svc
  namespace: secureworks
spec:
  type: NodePort
  selector:
    app: secureworks-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080