apiVersion: v1
kind: Service
metadata:
  name: secureworks-frontend-svc
spec:
  type: NodePort
  selector:
    app: secureworks-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080